# MongoDB 101

<img src="https://cdn.meme.am/images/11599433.jpg" alt="Title" style="width:350px"/>

## Welcome to MongoDB 101! Let's take a look at what we need to do today.
#### Step 1
* Log into https://mlab.com/ and create an account
* Create database within your account
* Create two users. One with read-only permissions. One without read-only permissions
* Follow the instructions below when you are ready

In [55]:
from pymongo import MongoClient

#This is the client. Replace my (username) and (password) with your non-readonly username and password
client = MongoClient("mongodb://cmyoung0718:Pissoff-1@ds031617.mlab.com:31617/cmydata")
#We get the database here. Don't forget to change the db name to your database name!
db = client.cmydata

In [56]:
test = db.test
print test

test.insert_one({'name':'Brad','age':29, 'color':'blue'})
test.insert_one({'name':'Brad','age':29, 'color':'blue'})
test.find_one()

Collection(Database(MongoClient(host=['ds031617.mlab.com:31617'], document_class=dict, tz_aware=False, connect=True), u'cmydata'), u'test')

{u'_id': ObjectId('580fa160fd904fa985a029ee'),
 u'age': 29,
 u'color': u'blue',
 u'name': u'Brad'}

In [57]:
test.remove()
test.insert_one({'name':'Brad','age':29, 'color':'blue'})

# Could also use querying stuff used on find on remove

/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: DeprecationWarning: remove is deprecated. Use delete_one or delete_many instead.
  if __name__ == '__main__':

## Navigate to wikipedia and pull down a table of your choice. Here is a sample of what I did to pull down the Harrison Ford movies table to help you out.

In [58]:
import urllib2
from bs4 import BeautifulSoup
import json
import pandas as pd

soup = BeautifulSoup(urllib2.urlopen('https://en.wikipedia.org/wiki/List_of_hairstyles').read())
tables = soup.find_all('table', class_="wikitable")
listy = []
for idx, table in enumerate(tables):
    if idx == 0:
        for idx2, row in enumerate(table.find_all('tr')):
            if idx2 > 0:
                datay = row.find_all('td')
                listy += [{'Hairstyle':datay[0].text,'Description':datay[2].text}]                
hair = pd.DataFrame(listy)
hair.head()

                                         Description       Hairstyle
0  Big hair hairstyle, natural comb-out, featured...            Afro
1  A haircut where the hair is longer on one side...  Asymmetric cut
2  Backcombing or teasing with hairspray to style...         Beehive
3  Bangs (or fringe) straight across the high for...     Bettie Page
4  Any hairstyle with large volume, though this i...        Big hair

## Now it's time to make our new mongodb document! Let's insert our wiki table's values into it.

In [59]:
#Creating a new table with the name table_name here
hairstyles = db.hair

#This removes everything from the table. Works on the same principle as find
hairstyles.remove({})

#To insert, just pass in the values one at a time
[hairstyles.insert_one(i) for i in listy]

/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:5: DeprecationWarning: remove is deprecated. Use delete_one or delete_many instead.

[<pymongo.results.InsertOneResult at 0x1152b6320>,
 <pymongo.results.InsertOneResult at 0x1152b62d0>,
 <pymongo.results.InsertOneResult at 0x1152b6280>,
 <pymongo.results.InsertOneResult at 0x1152b6230>,
 <pymongo.results.InsertOneResult at 0x1152b6190>,
 <pymongo.results.InsertOneResult at 0x1152b6050>,
 <pymongo.results.InsertOneResult at 0x1152b63c0>,
 <pymongo.results.InsertOneResult at 0x1152b6410>,
 <pymongo.results.InsertOneResult at 0x1152b6460>,
 <pymongo.results.InsertOneResult at 0x1152b64b0>,
 <pymongo.results.InsertOneResult at 0x1152b6500>,
 <pymongo.results.InsertOneResult at 0x1152b6550>,
 <pymongo.results.InsertOneResult at 0x1152b65a0>,
 <pymongo.results.InsertOneResult at 0x1152b65f0>,
 <pymongo.results.InsertOneResult at 0x1152b6640>,
 <pymongo.results.InsertOneResult at 0x1152b6690>,
 <pymongo.results.InsertOneResult at 0x1152b66e0>,
 <pymongo.results.InsertOneResult at 0x1152b6730>,
 <pymongo.results.InsertOneResult at 0x1152b6780>,
 <pymongo.results.InsertOneResult at 0x1152b67d0>,
 <pymongo.results.InsertOneResult at 0x1152b6820>,
 <pymongo.results.InsertOneResult at 0x1152b6870>,
 <pymongo.results.InsertOneResult at 0x1152b68c0>,
 <pymongo.results.InsertOneResult at 0x1152b6910>,
 <pymongo.results.InsertOneResult at 0x1152b6960>,
 <pymongo.results.InsertOneResult at 0x1152b69b0>,
 <pymongo.results.InsertOneResult at 0x1152b6a00>,
 <pymongo.results.InsertOneResult at 0x1152b6a50>,
 <pymongo.results.InsertOneResult at 0x1152b6aa0>,
 <pymongo.results.InsertOneResult at 0x1152b6af0>,
 <pymongo.results.InsertOneResult at 0x1152b6b40>,
 <pymongo.results.InsertOneResult at 0x1152b6b90>,
 <pymongo.results.InsertOneResult at 0x1152b6be0>,
 <pymongo.results.InsertOneResult at 0x1152b60f0>,
 <pymongo.results.InsertOneResult at 0x1152b61e0>,
 <pymongo.results.InsertOneResult at 0x1152b6140>,
 <pymongo.results.InsertOneResult at 0x1152b60a0>,
 <pymongo.results.InsertOneResult at 0x1152b6c30>,
 <pymongo.results.InsertOneResult at 0x1152b6c80>,
 <pymongo.results.InsertOneResult at 0x1152b6cd0>,
 <pymongo.results.InsertOneResult at 0x1152b6d20>,
 <pymongo.results.InsertOneResult at 0x1152b6d70>,
 <pymongo.results.InsertOneResult at 0x1152b6dc0>,
 <pymongo.results.InsertOneResult at 0x1152b6e10>,
 <pymongo.results.InsertOneResult at 0x1152b6e60>,
 <pymongo.results.InsertOneResult at 0x1152b6eb0>,
 <pymongo.results.InsertOneResult at 0x1152b6f00>,
 <pymongo.results.InsertOneResult at 0x1152b6f50>,
 <pymongo.results.InsertOneResult at 0x1152b6fa0>,
 <pymongo.results.InsertOneResult at 0x1152be050>,
 <pymongo.results.InsertOneResult at 0x1152be0a0>,
 <pymongo.results.InsertOneResult at 0x1152be0f0>,
 <pymongo.results.InsertOneResult at 0x1152be190>,
 <pymongo.results.InsertOneResult at 0x1152be230>,
 <pymongo.results.InsertOneResult at 0x1152be140>,
 <pymongo.results.InsertOneResult at 0x1152be280>,
 <pymongo.results.InsertOneResult at 0x1152be2d0>,
 <pymongo.results.InsertOneResult at 0x1152be320>,
 <pymongo.results.InsertOneResult at 0x1152be370>,
 <pymongo.results.InsertOneResult at 0x1152be410>,
 <pymongo.results.InsertOneResult at 0x1152be460>,
 <pymongo.results.InsertOneResult at 0x1152be3c0>,
 <pymongo.results.InsertOneResult at 0x1152be4b0>,
 <pymongo.results.InsertOneResult at 0x1152be500>,
 <pymongo.results.InsertOneResult at 0x1152be550>,
 <pymongo.results.InsertOneResult at 0x1152be5a0>,
 <pymongo.results.InsertOneResult at 0x1152be5f0>,
 <pymongo.results.InsertOneResult at 0x1152be640>,
 <pymongo.results.InsertOneResult at 0x1152be690>,
 <pymongo.results.InsertOneResult at 0x1152be6e0>,
 <pymongo.results.InsertOneResult at 0x1152be730>,
 <pymongo.results.InsertOneResult at 0x1152be780>,
 <pymongo.results.InsertOneResult at 0x1152be7d0>,
 <pymongo.results.InsertOneResult at 0x1152be820>,
 <pymongo.results.InsertOneResult at 0x1152be870>,
 <pymongo.results.InsertOneResult at 0x1152be8c0>,
 <pymongo.results.InsertOneResult at 0x1152be910>,
 <pymongo.results.InsertOneResult at 0x1152be960>,
 <pymongo.results.InsertOneResult at 0x1152be9b0>,
 <pymongo.results.InsertOneResult at 0x1152bea00>,
 <pymongo.results.InsertOneResult at 0x1152bea50>,
 <pymongo.results.InsertOneResult at 0x1152beaa0>,
 <pymongo.results.InsertOneResult at 0x1152beaf0>,
 <pymongo.results.InsertOneResult at 0x1152beb40>,
 <pymongo.results.InsertOneResult at 0x1152beb90>,
 <pymongo.results.InsertOneResult at 0x1152bebe0>,
 <pymongo.results.InsertOneResult at 0x1152bec30>,
 <pymongo.results.InsertOneResult at 0x1152bec80>,
 <pymongo.results.InsertOneResult at 0x1152becd0>,
 <pymongo.results.InsertOneResult at 0x1152bed20>,
 <pymongo.results.InsertOneResult at 0x1152bed70>,
 <pymongo.results.InsertOneResult at 0x1152bedc0>,
 <pymongo.results.InsertOneResult at 0x1152bee10>,
 <pymongo.results.InsertOneResult at 0x1152bee60>,
 <pymongo.results.InsertOneResult at 0x1152beeb0>,
 <pymongo.results.InsertOneResult at 0x1152bef00>,
 <pymongo.results.InsertOneResult at 0x1152bef50>,
 <pymongo.results.InsertOneResult at 0x1152befa0>,
 <pymongo.results.InsertOneResult at 0x115f47050>,
 <pymongo.results.InsertOneResult at 0x115f470a0>,
 <pymongo.results.InsertOneResult at 0x115f470f0>,
 <pymongo.results.InsertOneResult at 0x115f47140>,
 <pymongo.results.InsertOneResult at 0x115f47190>,
 <pymongo.results.InsertOneResult at 0x115f471e0>,
 <pymongo.results.InsertOneResult at 0x115f47230>,
 <pymongo.results.InsertOneResult at 0x115f47280>,
 <pymongo.results.InsertOneResult at 0x115f472d0>,
 <pymongo.results.InsertOneResult at 0x115f47320>,
 <pymongo.results.InsertOneResult at 0x115f47370>,
 <pymongo.results.InsertOneResult at 0x115f473c0>,
 <pymongo.results.InsertOneResult at 0x115f47410>,
 <pymongo.results.InsertOneResult at 0x115f47460>,
 <pymongo.results.InsertOneResult at 0x115f474b0>,
 <pymongo.results.InsertOneResult at 0x115f47500>,
 <pymongo.results.InsertOneResult at 0x115f47550>,
 <pymongo.results.InsertOneResult at 0x115f475a0>]

## Awesome! Now find the read-only user in your mongolab account. You are going to be passing this to your partner in the class. Don't be shy. Everyone has to do it.

In [6]:
# Pass your string to another student. 
# Don't forget to change the username and password to your other user's username and password!
# Here is a reminder of what that string looks like
# "mongodb://(username):(password)@ds063946.mlab.com:63946/(database_name)"

## Open the database you received from your partner. What is the data telling you? What kind of job roles would you imagine dealing with this data?

In [76]:
def printTables(db):
    collection = db.collection_names(include_system_collections=False)
    for collect in collection:
        print collect

client2 = MongoClient('mongodb://guest:pass@ds031925.mlab.com:31925/naytest')
db = client2.naytest

tallest = db.tallest
for i in tallest.find({}):
    print i

{u'City': u'Riyadh', u'Name': u'Burj Rafal', u'Country': u'\xa0Saudi Arabia', u'Height in meters': u'308\xa0m', u'Rank': u'100', u'Floors': u'68', u'Height in feet': u'1,010\xa0ft', u'_id': ObjectId('580fab78496a9d059fc6f780')}
{u'City': u'Kunming', u'Name': u'Wanda Plaza 1[19]', u'Country': u'\xa0China', u'Height in meters': u'307\xa0m', u'Rank': u'101', u'Floors': u'70', u'Height in feet': u'1,008\xa0ft', u'_id': ObjectId('580fab78496a9d059fc6f781')}
{u'City': u'Kunming', u'Name': u'Wanda Plaza 2[20]', u'Country': u'\xa0China', u'Height in meters': u'307\xa0m', u'Rank': u'Wanda Plaza 2[20]', u'Floors': u'70', u'Height in feet': u'1,008\xa0ft', u'_id': ObjectId('580fab79496a9d059fc6f782')}
{u'City': u'Chicago', u'Name': u'Franklin Center', u'Country': u'\xa0United States', u'Height in meters': u'307\xa0m', u'Rank': u'103', u'Floors': u'60', u'Height in feet': u'1,007\xa0ft', u'_id': ObjectId('580fab79496a9d059fc6f783')}
{u'City': u'Dubai', u'Name': u'Cayan Tower', u'Country': u'\xa0UAE', u'Height in meters': u'306\xa0m', u'Rank': u'104', u'Floors': u'76', u'Height in feet': u'1,005\xa0ft', u'_id': ObjectId('580fab79496a9d059fc6f784')}
{u'City': u'New York City', u'Name': u'One57', u'Country': u'\xa0United States', u'Height in meters': u'306\xa0m', u'Rank': u'105', u'Floors': u'75', u'Height in feet': u'1,004\xa0ft', u'_id': ObjectId('580fab79496a9d059fc6f785')}
{u'City': u'Shenzhen', u'Name': u'East Pacific Center Tower A', u'Country': u'\xa0China', u'Height in meters': u'306\xa0m', u'Rank': u'106', u'Floors': u'85', u'Height in feet': u'1,004\xa0ft', u'_id': ObjectId('580fab79496a9d059fc6f786')}
{u'City': u'London', u'Name': u'The Shard', u'Country': u'\xa0United Kingdom', u'Height in meters': u'306\xa0m', u'Rank': u'The Shard', u'Floors': u'73', u'Height in feet': u'1,004\xa0ft', u'_id': ObjectId('580fab79496a9d059fc6f787')}
{u'City': u'Houston', u'Name': u'JPMorgan Chase Tower', u'Country': u'\xa0United States', u'Height in meters': u'305\xa0m', u'Rank': u'108', u'Floors': u'75', u'Height in feet': u'1,002\xa0ft', u'_id': ObjectId('580fab79496a9d059fc6f788')}
{u'City': u'Abu Dhabi', u'Name': u'Etihad Tower 2[21][22]', u'Country': u'\xa0UAE', u'Height in meters': u'305\xa0m', u'Rank': u'109', u'Floors': u'79', u'Height in feet': u'1,002\xa0ft', u'_id': ObjectId('580fab79496a9d059fc6f789')}
{u'City': u'Incheon', u'Name': u'Northeast Asia Trade Tower', u'Country': u'\xa0South Korea', u'Height in meters': u'305\xa0m', u'Rank': u'110', u'Floors': u'68', u'Height in feet': u'1,001\xa0ft', u'_id': ObjectId('580fab79496a9d059fc6f78a')}
{u'City': u'Bangkok', u'Name': u'Baiyoke Tower II', u'Country': u'\xa0Thailand', u'Height in meters': u'304\xa0m', u'Rank': u'111', u'Floors': u'85', u'Height in feet': u'997\xa0ft', u'_id': ObjectId('580fab79496a9d059fc6f78b')}
{u'City': u'Wuxi', u'Name': u'Wuxi Maoye City - Marriott Hotel', u'Country': u'\xa0China', u'Height in meters': u'304\xa0m', u'Rank': u'112', u'Floors': u'68', u'Height in feet': u'997\xa0ft', u'_id': ObjectId('580fab79496a9d059fc6f78c')}
{u'City': u'Shenzhen', u'Name': u'Shenzhen CFC Changfu Centre', u'Country': u'\xa0China', u'Height in meters': u'304\xa0m', u'Rank': u'Shenzhen CFC Changfu Centre', u'Floors': u'68', u'Height in feet': u'997\xa0ft', u'_id': ObjectId('580fab79496a9d059fc6f78d')}
{u'City': u'Chicago', u'Name': u'Two Prudential Plaza', u'Country': u'\xa0United States', u'Height in meters': u'303\xa0m', u'Rank': u'114', u'Floors': u'64', u'Height in feet': u'995\xa0ft', u'_id': ObjectId('580fab79496a9d059fc6f78e')}
{u'City': u'Liuzhou', u'Name': u'Diwang International Fortune Center', u'Country': u'\xa0China', u'Height in meters': u'303\xa0m', u'Rank': u'115', u'Floors': u'75', u'Height in feet': u'994\xa0ft', u'_id': ObjectId('580fab79496a9d059fc6f78f')}
{u'City': u'Riyadh', u'Name': u'KAFD World Trade Center[23]', u'Country': u'\xa0Saudi Arabia', u'Height in meters': u'303\xa0m', u'Rank': u'KAFD World Trade Center[23]', u'Floors': u'67', u'Height in feet': u'994\xa0ft', u'_id': ObjectId('580fab79496a9d059fc6f790')}
{u'City': u'Jinan', u'Name': u'Greenland Puli Center[26]', u'Country': u'\xa0China', u'Height in meters': u'303\xa0m', u'Rank': u'Greenland Puli Center[26]', u'Floors': u'60', u'Height in feet': u'994\xa0ft', u'_id': ObjectId('580fab7a496a9d059fc6f793')}
{u'City': u'Guangzhou', u'Name': u'Leatop Plaza', u'Country': u'\xa0China', u'Height in meters': u'303\xa0m', u'Rank': u'120', u'Floors': u'65', u'Height in feet': u'993\xa0ft', u'_id': ObjectId('580fab7a496a9d059fc6f794')}
{u'City': u'Houston', u'Name': u'Wells Fargo Plaza', u'Country': u'\xa0United States', u'Height in meters': u'302\xa0m', u'Rank': u'121', u'Floors': u'71', u'Height in feet': u'992\xa0ft', u'_id': ObjectId('580fab7a496a9d059fc6f795')}
{u'City': u'Riyadh', u'Name': u'Kingdom Centre', u'Country': u'\xa0Saudi Arabia', u'Height in meters': u'302\xa0m', u'Rank': u'Kingdom Centre', u'Floors': u'41', u'Height in feet': u'992\xa0ft', u'_id': ObjectId('580fab7a496a9d059fc6f796')}
{u'City': u'Dubai', u'Name': u'The Address Downtown Burj Khalifa', u'Country': u'\xa0UAE', u'Height in meters': u'302\xa0m', u'Rank': u'123', u'Floors': u'63', u'Height in feet': u'991\xa0ft', u'_id': ObjectId('580fab7a496a9d059fc6f797')}
{u'City': u'Suzhou', u'Name': u'Gate of the Orient', u'Country': u'\xa0China', u'Height in meters': u'302\xa0m', u'Rank': u'124', u'Floors': u'68', u'Height in feet': u'990\xa0ft', u'_id': ObjectId('580fab7a496a9d059fc6f798')}
{u'City': u'Moscow', u'Name': u'Moscow Tower', u'Country': u'\xa0Russia', u'Height in meters': u'302\xa0m', u'Rank': u'125', u'Floors': u'76', u'Height in feet': u'989\xa0ft', u'_id': ObjectId('580fab7a496a9d059fc6f799')}
{u'City': u'Busan', u'Name': u"We've the Zenith Tower A", u'Country': u'\xa0South Korea', u'Height in meters': u'301\xa0m', u'Rank': u'126', u'Floors': u'80', u'Height in feet': u'984\xa0ft', u'_id': ObjectId('580fab7a496a9d059fc6f79a')}
{u'City': u'Changsha', u'Name': u'Huachuang International Plaza[27]', u'Country': u'\xa0China', u'Height in meters': u'301\xa0m', u'Rank': u'Huachuang International Plaza[27]', u'Floors': u'66', u'Height in feet': u'984\xa0ft', u'_id': ObjectId('580fab7a496a9d059fc6f79b')}
{u'City': u'Shenzhen', u'Name': u'Shenzhen Zhongzhou Holdings Financial Center Tower A', u'Country': u'\xa0China', u'Height in meters': u'301\xa0m', u'Rank': u'128', u'Floors': u'61', u'Height in feet': u'987\xa0ft', u'_id': ObjectId('580fab7a496a9d059fc6f79c')}
{u'City': u'Santiago', u'Name': u'Gran Torre Santiago', u'Country': u'\xa0Chile', u'Height in meters': u'300\xa0m', u'Rank': u'129', u'Floors': u'62', u'Height in feet': u'984\xa0ft', u'_id': ObjectId('580fab7a496a9d059fc6f79d')}
{u'City': u'Osaka', u'Name': u'Abeno Harukas', u'Country': u'\xa0Japan', u'Height in meters': u'300\xa0m', u'Rank': u'Abeno Harukas', u'Floors': u'60', u'Height in feet': u'984\xa0ft', u'_id': ObjectId('580fab7a496a9d059fc6f79e')}
{u'City': u'Kuwait City', u'Name': u'Arraya 2', u'Country': u'\xa0Kuwait', u'Height in meters': u'300\xa0m', u'Rank': u'Arraya 2', u'Floors': u'60', u'Height in feet': u'984\xa0ft', u'_id': ObjectId('580fab7b496a9d059fc6f79f')}
{u'City': u'Doha', u'Name': u'Aspire Tower', u'Country': u'\xa0Qatar', u'Height in meters': u'300\xa0m', u'Rank': u'Aspire Tower', u'Floors': u'36', u'Height in feet': u'984\xa0ft', u'_id': ObjectId('580fab7b496a9d059fc6f7a0')}
{u'City': u'Dubai', u'Name': u'Burj Khalifa\u2605', u'Country': u'\xa0UAE', u'Height in meters': u'828\xa0m', u'Rank': u'1', u'Floors': u'163', u'Height in feet': u'2,717\xa0ft', u'_id': ObjectId('580fab72496a9d059fc6f71d')}
{u'City': u'Shanghai', u'Name': u'Shanghai Tower', u'Country': u'\xa0China', u'Height in meters': u'632\xa0m[10]', u'Rank': u'2', u'Floors': u'128', u'Height in feet': u'2,073\xa0ft', u'_id': ObjectId('580fab72496a9d059fc6f71e')}
{u'City': u'Mecca', u'Name': u'Abraj Al-Bait Clock Tower', u'Country': u'\xa0Saudi Arabia', u'Height in meters': u'601\xa0m[11]', u'Rank': u'3', u'Floors': u'120', u'Height in feet': u'1,971\xa0ft', u'_id': ObjectId('580fab72496a9d059fc6f71f')}
{u'City': u'Shenzhen', u'Name': u'Ping An Finance Centre', u'Country': u'\xa0China', u'Height in meters': u'600\xa0m', u'Rank': u'4', u'Floors': u'115', u'Height in feet': u'1,969\xa0ft', u'_id': ObjectId('580fab72496a9d059fc6f720')}
{u'City': u'Seoul', u'Name': u'Lotte World Tower', u'Country': u'\xa0South Korea', u'Height in meters': u'555\xa0m', u'Rank': u'5', u'Floors': u'123', u'Height in feet': u'1,823\xa0ft', u'_id': ObjectId('580fab72496a9d059fc6f721')}
{u'City': u'New York City', u'Name': u'One World Trade Center', u'Country': u'\xa0United States', u'Height in meters': u'541\xa0m', u'Rank': u'6', u'Floors': u'104', u'Height in feet': u'1,776\xa0ft', u'_id': ObjectId('580fab72496a9d059fc6f722')}
{u'City': u'Guangzhou', u'Name': u'CTF Finance Centre', u'Country': u'\xa0China', u'Height in meters': u'530\xa0m[12]', u'Rank': u'7', u'Floors': u'111', u'Height in feet': u'1,740\xa0ft', u'_id': ObjectId('580fab72496a9d059fc6f723')}
{u'City': u'Taipei', u'Name': u'Taipei 101', u'Country': u'\xa0Taiwan', u'Height in meters': u'509\xa0m[13]', u'Rank': u'8', u'Floors': u'101', u'Height in feet': u'1,670\xa0ft', u'_id': ObjectId('580fab72496a9d059fc6f724')}
{u'City': u'Shanghai', u'Name': u'Shanghai World Financial Center', u'Country': u'\xa0China', u'Height in meters': u'492\xa0m', u'Rank': u'9', u'Floors': u'101', u'Height in feet': u'1,614\xa0ft', u'_id': ObjectId('580fab72496a9d059fc6f725')}
{u'City': u'Hong Kong', u'Name': u'International Commerce Centre', u'Country': u'\xa0Hong Kong', u'Height in meters': u'484\xa0m', u'Rank': u'10', u'Floors': u'118', u'Height in feet': u'1,588\xa0ft', u'_id': ObjectId('580fab72496a9d059fc6f726')}
{u'City': u'Kuala Lumpur', u'Name': u'Petronas Tower 1', u'Country': u'\xa0Malaysia', u'Height in meters': u'452\xa0m', u'Rank': u'11', u'Floors': u'88', u'Height in feet': u'1,483\xa0ft', u'_id': ObjectId('580fab72496a9d059fc6f727')}
{u'City': u'Kuala Lumpur', u'Name': u'Petronas Tower 2', u'Country': u'\xa0Malaysia', u'Height in meters': u'452\xa0m', u'Rank': u'Petronas Tower 2', u'Floors': u'88', u'Height in feet': u'1,483\xa0ft', u'_id': ObjectId('580fab72496a9d059fc6f728')}
{u'City': u'Nanjing', u'Name': u'Zifeng Tower', u'Country': u'\xa0China', u'Height in meters': u'450\xa0m', u'Rank': u'13', u'Floors': u'89', u'Height in feet': u'1,476\xa0ft', u'_id': ObjectId('580fab72496a9d059fc6f729')}
{u'City': u'Chicago', u'Name': u'Willis Tower (formerly the Sears Tower)', u'Country': u'\xa0United States', u'Height in meters': u'442\xa0m', u'Rank': u'14', u'Floors': u'108', u'Height in feet': u'1,451\xa0ft\xa0', u'_id': ObjectId('580fab73496a9d059fc6f72a')}
{u'City': u'Shenzhen', u'Name': u'KK100', u'Country': u'\xa0China', u'Height in meters': u'442\xa0m', u'Rank': u'15', u'Floors': u'100', u'Height in feet': u'1,449\xa0ft', u'_id': ObjectId('580fab73496a9d059fc6f72b')}
{u'City': u'Guangzhou', u'Name': u'Guangzhou International Finance Center', u'Country': u'\xa0China', u'Height in meters': u'440\xa0m', u'Rank': u'16', u'Floors': u'103', u'Height in feet': u'1,440\xa0ft', u'_id': ObjectId('580fab73496a9d059fc6f72c')}
{u'City': u'Wuhan', u'Name': u'Wuhan Center', u'Country': u'\xa0China', u'Height in meters': u'438\xa0m', u'Rank': u'17', u'Floors': u'88', u'Height in feet': u'1,437\xa0ft', u'_id': ObjectId('580fab73496a9d059fc6f72d')}
{u'City': u'Dubai', u'Name': u'Marina 101', u'Country': u'\xa0UAE', u'Height in meters': u'427\xa0m', u'Rank': u'18', u'Floors': u'101', u'Height in feet': u'1,399\xa0ft', u'_id': ObjectId('580fab73496a9d059fc6f72e')}
{u'City': u'New York City', u'Name': u'432 Park Avenue', u'Country': u'\xa0United States', u'Height in meters': u'426\xa0m', u'Rank': u'19', u'Floors': u'88', u'Height in feet': u'1,397\xa0ft', u'_id': ObjectId('580fab73496a9d059fc6f72f')}
{u'City': u'Chicago', u'Name': u'Trump International Hotel and Tower[14]', u'Country': u'\xa0United States', u'Height in meters': u'423\xa0m', u'Rank': u'20', u'Floors': u'98', u'Height in feet': u'1,389\xa0ft', u'_id': ObjectId('580fab73496a9d059fc6f730')}
{u'City': u'Shanghai', u'Name': u'Jin Mao Tower', u'Country': u'\xa0China', u'Height in meters': u'421\xa0m', u'Rank': u'21', u'Floors': u'88', u'Height in feet': u'1,380\xa0ft', u'_id': ObjectId('580fab73496a9d059fc6f731')}
{u'City': u'Dubai', u'Name': u'Princess Tower', u'Country': u'\xa0UAE', u'Height in meters': u'414\xa0m', u'Rank': u'22', u'Floors': u'101', u'Height in feet': u'1,358\xa0ft[15]', u'_id': ObjectId('580fab73496a9d059fc6f732')}
{u'City': u'Kuwait City', u'Name': u'Al Hamra Tower', u'Country': u'\xa0Kuwait', u'Height in meters': u'413\xa0m', u'Rank': u'23', u'Floors': u'80', u'Height in feet': u'1,354\xa0ft', u'_id': ObjectId('580fab73496a9d059fc6f733')}
{u'City': u'Hong Kong', u'Name': u'Two International Finance Centre', u'Country': u'\xa0Hong Kong', u'Height in meters': u'412\xa0m', u'Rank': u'24', u'Floors': u'88', u'Height in feet': u'1,352\xa0ft', u'_id': ObjectId('580fab73496a9d059fc6f734')}
{u'City': u'Dubai', u'Name': u'23 Marina', u'Country': u'\xa0UAE', u'Height in meters': u'395\xa0m', u'Rank': u'25', u'Floors': u'89', u'Height in feet': u'1,296\xa0ft', u'_id': ObjectId('580fab73496a9d059fc6f735')}
{u'City': u'Guangzhou', u'Name': u'CITIC Plaza', u'Country': u'\xa0China', u'Height in meters': u'391\xa0m', u'Rank': u'26', u'Floors': u'80', u'Height in feet': u'1,283\xa0ft', u'_id': ObjectId('580fab73496a9d059fc6f736')}
{u'City': u'Shenzhen', u'Name': u'Shun Hing Square', u'Country': u'\xa0China', u'Height in meters': u'384\xa0m', u'Rank': u'27', u'Floors': u'69', u'Height in feet': u'1,260\xa0ft', u'_id': ObjectId('580fab73496a9d059fc6f737')}
{u'City': u'Dalian', u'Name': u'Eton Place Dalian Tower 1', u'Country': u'\xa0China', u'Height in meters': u'383\xa0m', u'Rank': u'28', u'Floors': u'81', u'Height in feet': u'1,257\xa0ft', u'_id': ObjectId('580fab73496a9d059fc6f738')}
{u'City': u'Abu Dhabi', u'Name': u'Burj Mohammed bin Rashid', u'Country': u'\xa0UAE', u'Height in meters': u'381\xa0m', u'Rank': u'29', u'Floors': u'88', u'Height in feet': u'1,251\xa0ft', u'_id': ObjectId('580fab74496a9d059fc6f739')}
{u'City': u'New York City', u'Name': u'Empire State Building', u'Country': u'\xa0United States', u'Height in meters': u'381\xa0m', u'Rank': u'30', u'Floors': u'102', u'Height in feet': u'1,250\xa0ft', u'_id': ObjectId('580fab74496a9d059fc6f73a')}
{u'City': u'Dubai', u'Name': u'Elite Residence', u'Country': u'\xa0UAE', u'Height in meters': u'381\xa0m', u'Rank': u'31', u'Floors': u'87', u'Height in feet': u'1,248\xa0ft', u'_id': ObjectId('580fab74496a9d059fc6f73b')}
{u'City': u'Hong Kong', u'Name': u'Central Plaza', u'Country': u'\xa0Hong Kong', u'Height in meters': u'374\xa0m', u'Rank': u'32', u'Floors': u'78', u'Height in feet': u'1,227\xa0ft', u'_id': ObjectId('580fab74496a9d059fc6f73c')}
{u'City': u'Moscow', u'Name': u'Federation Tower (East Tower)[16]', u'Country': u'\xa0Russia', u'Height in meters': u'374\xa0m', u'Rank': u'33', u'Floors': u'95', u'Height in feet': u'1,226\xa0ft', u'_id': ObjectId('580fab74496a9d059fc6f73d')}
{u'City': u'Dalian', u'Name': u'Dalian International Trade Center', u'Country': u'\xa0China', u'Height in meters': u'370\xa0m', u'Rank': u'34', u'Floors': u'86', u'Height in feet': u'1,214\xa0ft', u'_id': ObjectId('580fab74496a9d059fc6f73e')}
{u'City': u'Dubai', u'Name': u'The Address the BLVD', u'Country': u'\xa0UAE', u'Height in meters': u'368\xa0m', u'Rank': u'35', u'Floors': u'72', u'Height in feet': u'1,207\xa0ft', u'_id': ObjectId('580fab74496a9d059fc6f73f')}
{u'City': u'Hong Kong', u'Name': u'Bank of China Tower', u'Country': u'\xa0Hong Kong', u'Height in meters': u'367\xa0m', u'Rank': u'36', u'Floors': u'70', u'Height in feet': u'1,205\xa0ft', u'_id': ObjectId('580fab74496a9d059fc6f740')}
{u'City': u'New York City', u'Name': u'Bank of America Tower', u'Country': u'\xa0United States', u'Height in meters': u'366\xa0m', u'Rank': u'37', u'Floors': u'54', u'Height in feet': u'1,200\xa0ft', u'_id': ObjectId('580fab74496a9d059fc6f741')}
{u'City': u'Dubai', u'Name': u'Almas Tower', u'Country': u'\xa0UAE', u'Height in meters': u'363\xa0m', u'Rank': u'38', u'Floors': u'68', u'Height in feet': u'1,191\xa0ft', u'_id': ObjectId('580fab74496a9d059fc6f742')}
{u'City': u'Dubai', u'Name': u'JW Marriott Marquis Dubai Tower 1', u'Country': u'\xa0UAE', u'Height in meters': u'355\xa0m', u'Rank': u'39', u'Floors': u'82', u'Height in feet': u'1,166\xa0ft', u'_id': ObjectId('580fab74496a9d059fc6f743')}
{u'City': u'Dubai', u'Name': u'JW Marriott Marquis Dubai Tower 2', u'Country': u'\xa0UAE', u'Height in meters': u'355\xa0m', u'Rank': u'JW Marriott Marquis Dubai Tower 2', u'Floors': u'82', u'Height in feet': u'1,166\xa0ft', u'_id': ObjectId('580fab74496a9d059fc6f744')}
{u'City': u'Dubai', u'Name': u'Emirates Office Tower', u'Country': u'\xa0UAE', u'Height in meters': u'355\xa0m', u'Rank': u'41', u'Floors': u'54', u'Height in feet': u'1,163\xa0ft', u'_id': ObjectId('580fab74496a9d059fc6f745')}
{u'City': u'Moscow', u'Name': u'OKO Tower - South Tower', u'Country': u'\xa0Russia', u'Height in meters': u'354\xa0m', u'Rank': u'42', u'Floors': u'85', u'Height in feet': u'1,160\xa0ft', u'_id': ObjectId('580fab74496a9d059fc6f746')}
{u'City': u'Dubai', u'Name': u'The Marina Torch', u'Country': u'\xa0UAE', u'Height in meters': u'352\xa0m', u'Rank': u'43', u'Floors': u'86', u'Height in feet': u'1,155\xa0ft', u'_id': ObjectId('580fab74496a9d059fc6f747')}
{u'City': u'Shenyang', u'Name': u'Forum 66 Tower 2', u'Country': u'\xa0China', u'Height in meters': u'351\xa0m', u'Rank': u'44', u'Floors': u'68', u'Height in feet': u'1,150\xa0ft', u'_id': ObjectId('580fab75496a9d059fc6f748')}
{u'City': u'Guangzhou', u'Name': u'The Pinnacle', u'Country': u'\xa0China', u'Height in meters': u'350\xa0m', u'Rank': u'45', u'Floors': u'60', u'Height in feet': u'1,149\xa0ft', u'_id': ObjectId('580fab75496a9d059fc6f749')}
{u'City': u'Las Vegas', u'Name': u'Stratosphere Las Vegas', u'Country': u'\xa0United States', u'Height in meters': u'350\xa0m', u'Rank': u'Stratosphere Las Vegas', u'Floors': u'N/A', u'Height in feet': u'1,149\xa0ft', u'_id': ObjectId('580fab75496a9d059fc6f74a')}
{u'City': u'Kaohsiung', u'Name': u'Tuntex Sky Tower', u'Country': u'\xa0Taiwan', u'Height in meters': u'347\xa0m', u'Rank': u'47', u'Floors': u'85', u'Height in feet': u'1,140\xa0ft', u'_id': ObjectId('580fab75496a9d059fc6f74b')}
{u'City': u'Chicago', u'Name': u'Aon Center', u'Country': u'\xa0United States', u'Height in meters': u'346\xa0m', u'Rank': u'48', u'Floors': u'83', u'Height in feet': u'1,136\xa0ft', u'_id': ObjectId('580fab75496a9d059fc6f74c')}
{u'City': u'Hong Kong', u'Name': u'The Center', u'Country': u'\xa0Hong Kong', u'Height in meters': u'346\xa0m', u'Rank': u'49', u'Floors': u'73', u'Height in feet': u'1,135\xa0ft', u'_id': ObjectId('580fab75496a9d059fc6f74d')}
{u'City': u'Chicago', u'Name': u'John Hancock Center', u'Country': u'\xa0United States', u'Height in meters': u'344\xa0m', u'Rank': u'50', u'Floors': u'100', u'Height in feet': u'1,128\xa0ft', u'_id': ObjectId('580fab75496a9d059fc6f74e')}
{u'City': u'Abu Dhabi', u'Name': u'ADNOC Headquarters', u'Country': u'\xa0UAE', u'Height in meters': u'342\xa0m', u'Rank': u'51', u'Floors': u'76', u'Height in feet': u'1,122\xa0ft', u'_id': ObjectId('580fab75496a9d059fc6f74f')}
{u'City': u'Dubai', u'Name': u'Ahmed Abdul Rahim Al Attar Tower', u'Country': u'\xa0UAE', u'Height in meters': u'342\xa0m', u'Rank': u'Ahmed Abdul Rahim Al Attar Tower', u'Floors': u'76', u'Height in feet': u'1,122\xa0ft', u'_id': ObjectId('580fab75496a9d059fc6f750')}
{u'City': u'Wuxi', u'Name': u'The Wharf Times Square', u'Country': u'\xa0China', u'Height in meters': u'339\xa0m', u'Rank': u'53', u'Floors': u'68', u'Height in feet': u'1,112\xa0ft', u'_id': ObjectId('580fab75496a9d059fc6f751')}

## Was the data cleaned before you got it? Is information missing that might keep you from figuring out what the data represents?

The data is relatively clean.  Some of the rows have the wrong information in them.  Columns that should probably be strings are not strings, but that's not too bad.

In [77]:
df_tall = pd.DataFrame([i for i in tallest.find({})])
df_tall

,City,Country,Floors,Height in feet,Height in meters,Name,Rank,_id
0,Riyadh,Saudi Arabia,68,"1,010 ft",308 m,Burj Rafal,100,580fab78496a9d059fc6f780
1,Kunming,China,70,"1,008 ft",307 m,Wanda Plaza 1[19],101,580fab78496a9d059fc6f781
2,Kunming,China,70,"1,008 ft",307 m,Wanda Plaza 2[20],Wanda Plaza 2[20],580fab79496a9d059fc6f782
3,Chicago,United States,60,"1,007 ft",307 m,Franklin Center,103,580fab79496a9d059fc6f783
4,Dubai,UAE,76,"1,005 ft",306 m,Cayan Tower,104,580fab79496a9d059fc6f784
5,New York City,United States,75,"1,004 ft",306 m,One57,105,580fab79496a9d059fc6f785
6,Shenzhen,China,85,"1,004 ft",306 m,East Pacific Center Tower A,106,580fab79496a9d059fc6f786
7,London,United Kingdom,73,"1,004 ft",306 m,The Shard,The Shard,580fab79496a9d059fc6f787
8,Houston,United States,75,"1,002 ft",305 m,JPMorgan Chase Tower,108,580fab79496a9d059fc6f788
9,Abu Dhabi,UAE,79,"1,002 ft",305 m,Etihad Tower 2[21][22],109,580fab79496a9d059fc6f789
10,Incheon,South Korea,68,"1,001 ft",305 m,Northeast Asia Trade Tower,110,580fab79496a9d059fc6f78a
11,Bangkok,Thailand,85,997 ft,304 m,Baiyoke Tower II,111,580fab79496a9d059fc6f78b
12,Wuxi,China,68,997 ft,304 m,Wuxi Maoye City - Marriott Hotel,112,580fab79496a9d059fc6f78c
13,Shenzhen,China,68,997 ft,304 m,Shenzhen CFC Changfu Centre,Shenzhen CFC Changfu Centre,580fab79496a9d059fc6f78d
14,Chicago,United States,64,995 ft,303 m,Two Prudential Plaza,114,580fab79496a9d059fc6f78e
15,Liuzhou,China,75,994 ft,303 m,Diwang International Fortune Center,115,580fab79496a9d059fc6f78f
16,Riyadh,Saudi Arabia,67,994 ft,303 m,KAFD World Trade Center[23],KAFD World Trade Center[23],580fab79496a9d059fc6f790
17,Jinan,China,60,994 ft,303 m,Greenland Puli Center[26],Greenland Puli Center[26],580fab7a496a9d059fc6f793
18,Guangzhou,China,65,993 ft,303 m,Leatop Plaza,120,580fab7a496a9d059fc6f794
19,Houston,United States,71,992 ft,302 m,Wells Fargo Plaza,121,580fab7a496a9d059fc6f795
20,Riyadh,Saudi Arabia,41,992 ft,302 m,Kingdom Centre,Kingdom Centre,580fab7a496a9d059fc6f796
21,Dubai,UAE,63,991 ft,302 m,The Address Downtown Burj Khalifa,123,580fab7a496a9d059fc6f797
22,Suzhou,China,68,990 ft,302 m,Gate of the Orient,124,580fab7a496a9d059fc6f798
23,Moscow,Russia,76,989 ft,302 m,Moscow Tower,125,580fab7a496a9d059fc6f799
24,Busan,South Korea,80,984 ft,301 m,We've the Zenith Tower A,126,580fab7a496a9d059fc6f79a
25,Changsha,China,66,984 ft,301 m,Huachuang International Plaza[27],Huachuang International Plaza[27],580fab7a496a9d059fc6f79b
26,Shenzhen,China,61,987 ft,301 m,Shenzhen Zhongzhou Holdings Financial Center T...,128,580fab7a496a9d059fc6f79c
27,Santiago,Chile,62,984 ft,300 m,Gran Torre Santiago,129,580fab7a496a9d059fc6f79d
28,Osaka,Japan,60,984 ft,300 m,Abeno Harukas,Abeno Harukas,580fab7a496a9d059fc6f79e
29,Kuwait City,Kuwait,60,984 ft,300 m,Arraya 2,Arraya 2,580fab7b496a9d059fc6f79f
...,...,...,...,...,...,...,...,...
102,Wuxi,China,68,"1,076 ft",328 m,Wuxi Suning Plaza 1,Wuxi Suning Plaza 1,580fab76496a9d059fc6f764
103,Dubai,UAE,80,"1,070 ft",326 m,The Index,73,580fab77496a9d059fc6f765
104,Nanning,China,68,"1,066 ft",325 m,Guangxi Finance Plaza,74,580fab77496a9d059fc6f766
105,Abu Dhabi,UAE,72,"1,063 ft",324 m,The Landmark,75,580fab77496a9d059fc6f767
106,Nanjing,China,62,"1,063 ft",324 m,Deji Plaza Phase 2,Deji Plaza Phase 2,580fab77496a9d059fc6f768
107,Yantai,China,59,"1,060 ft",323 m,Yantai Shimao No.1 The Harbour,77,580fab77496a9d059fc6f769
108,Gold Coast,Australia,80,"1,058 ft",323 m,Q1,78,580fab77496a9d059fc6f76a
109,Wenzhou,China,68,"1,056 ft",322 m,Wenzhou World Trade Center,79,580fab77496a9d059fc6f76b
110,Dubai,UAE,60,"1,053 ft",321 m,Burj Al Arab,80,580fab77496a9d059fc6f76c
111,Hong Kong,Hong Kong,80,"1,051 ft",320 m,Nina Tower,81,580fab77496a9d059fc6f76d
112,Shanghai,China,66,"1,048 ft",320 m,Sinar Mas Center 1,82,580fab77496a9d059fc6f76e
113,New York City,United States,77,"1,046 ft",319 m,Chrysler Building,83,580fab77496a9d059fc6f76f
114,Guangzhou,China,67,"1,046 ft",319 m,Global City Square[17],Global City Square[17],580fab77496a9d059fc6f770
115,New York City,United States,52,"1,046 ft",319 m,New York Times Building,New York Times Building,580fab77496a9d059fc6f771
116,Dubai,UAE,72,"1,042 ft",317 m,HHHR Tower,86,580fab77496a9d059fc6f772
117,Chongqing,China,65,"1,037 ft",316 m,Chongqing IFS T1,87,580fab77496a9d059fc6f773
118,Nanjing,China,68,"1,032 ft",315 m,Nanjing International Youth Cultural Centre To...,88,580fab78496a9d059fc6f774
119,Changsha,China,65,"1,032 ft",315 m,Changsha IFS Tower T2,Changsha IFS Tower T2,580fab78496a9d059fc6f775
120,Bangkok,Thailand,75,"1,031 ft",314 m,MahaNakhon,90,580fab78496a9d059fc6f776
121,Atlanta,United States,55,"1,024 ft",312 m,Bank of America Plaza,91,580fab78496a9d059fc6f777
122,Shenyang,China,75,"1,020 ft",311 m,Moi Center,92,580fab78496a9d059fc6f778
123,Los Angeles,United States,73,"1,018 ft",310 m,U.S. Bank Tower,93,580fab78496a9d059fc6f779
124,Kuala Lumpur,Malaysia,55,"1,017 ft",310 m,Menara Telekom,94,580fab78496a9d059fc6f77a
125,Dubai,UAE,82,"1,017 ft",310 m,Ocean Heights,Ocean Heights,580fab78496a9d059fc6f77b
126,Guangzhou,China,71,"1,016 ft",310 m,Pearl River Tower,96,580fab78496a9d059fc6f77c
127,Guangzhou,China,68,"1,015 ft",309 m,Fortune Center,97,580fab78496a9d059fc6f77d
128,Dubai,UAE,56,"1,014 ft",309 m,Jumeirah Emirates Towers Hotel,98,580fab78496a9d059fc6f77e
129,Moscow,Russia,72,"1,013 ft",309 m,Stalnaya Vershina,99,580fab78496a9d059fc6f77f
130,Nanchang,China,59,994 ft,303 m,Jiangxi Nanchang Greenland Central Plaza 1[24],Jiangxi Nanchang Greenland Central Plaza 1[24],580fab7a496a9d059fc6f791
131,Nanchang,China,59,994 ft,303 m,Jiangxi Nanchang Greenland Central Plaza 2[25],Jiangxi Nanchang Greenland Central Plaza 2[25],580fab7a496a9d059fc6f792

## Do some exploratory data analysis on the table. Did you find anything surprising?

In [ ]:
# There was a 'N/A' in the floors column
df_tall = df_tall.ix[df_tall['Floors'] != 'N/A']
df_tall['Floors'] = [float(i) for i in df_tall['Floors']]

## Come up with three solvable questions to ask your partner regarding his data. Each should test your knowledge of regular expressions and mongodb. Feel free to look up new ways to do things. Put the questions and the answers to those questions here.

1. What is the average number of floors for a building in this list?
2. How many of the builidings are in the United States?
3. How many buildings are over 1,000 ft?

In [104]:
# What is the average number of floors for a building in this list?
import numpy as np
np.mean(df_tall['Floors'])

77.38167938931298

In [121]:
# How many of the builidings are in the United States?
listy = []
for idx, i in enumerate(tallest.find({'Country': {'$regex' : 'States$'}})):
    listy.append(idx+1)
listy[-1]

19

In [131]:
# How many buildings are over 1,000 ft?
listy = []
for idx, i in enumerate(tallest.find({'Height in feet': {'$regex' : '.*[0-9]{1},.*'}})):
    listy.append(idx+1)
listy[-1]

110

## Solve the questions your partner gave to you. This is for helping you to get more acquianted with these concepts, so try not to give away your answers.

1. How many hairstyles are longer than 7 letters
2. How many hairstyles are 2 or more words?
3. Which hairstlyes start with the letter 'B'

In [84]:
# How many hairstyles are longer than 7 letters
listy = []
for idx, i in enumerate(hairstyles.find({'Hairstyle': {'$regex' : '^\w{8}'}})):
    listy.append(idx+1)
listy[-1]

27

In [81]:
# How many hairstyles are 2 or more words?
listy = []
for idx, i in enumerate(hairstyles.find({'Hairstyle': {'$regex' : '^\W*\w+\s{1}\w+\W*$'}})):
    listy.append(idx+1)
listy[-1]

54

In [87]:
# Which hairstlyes start with the letter 'B'
listy = []
for i in (hairstyles.find({'Hairstyle' : {'$regex' : '^B.*'}})):
    print i['Hairstyle']

Beehive
Bettie Page
Blow Out
Blunt cut
Bob cut
Bouffant
Bowl cut
Braid
Brush cut
Bun
Bunches
Burr
Business-man cut
Butch cut
Buzz cut
Big hair

## Try inserting a document into your partner's database. What happens? Why do you think that is?

It doesn't work because I have read-only access to the database.